dist: xenial
language: python
python: '3.7'
env: LC_ALL=C.UTF-8 LANG=C.UTF-8
install:
- ./pycli init
- ./pycli lock
- ./pycli init
script:
- venv/bin/tox
deploy:
  provider: script
  script: ./pycli init && ./pycli build &&./pycli upload
  on:
    tags: true
    branches:
      only:
        - master
